%\VignetteIndexEntry{Bio3D Overview}
%\VignetteDepends{}
%\VignetteKeywords{Documentation}
%\VignettePackage{Bio3D}

\documentclass[letter]{article}
%% \documentclass[12pt]{article}
\usepackage{natbib}
\usepackage{color}
\definecolor{myurlblue}{rgb}{0.3,0.2,0.7}
\usepackage[colorlinks=true,urlcolor=myurlblue,pagecolor=black,citecolor=myurlbl
ue,linkcolor=black]{hyperref}


\usepackage{times}
\usepackage{hyperref}


\textwidth=6.2in
\textheight=8.5in
%\parskip=.3cm
\oddsidemargin=.1in
\evensidemargin=.1in
\headheight=-.3in

\begin{document}

\title{Bio3D Installation and Overview}
\maketitle


\section{Introduction}
The aim of this document, termed a vignette\footnote{This vignette contains executable examples, see \texttt{help(vignette)} for further details.} in R parlance, is to provide a brief introduction to the bio3d R package \citep{grant06}.  A number of other bio3d package vignettes are available, including: \texttt{Comparative protein structure analysis with Bio3D}, \texttt{Introduction to sequence conservation analysis with Bio3D} and \texttt{Basic trajectory analysis with Bio3D}.  In this vignette we will demonstrate ...


\paragraph{Supporting Material:}
The latest version, full documentation and furhter vignettes can be obtained from the bio3d website: \href{http://mccammon.ucsd.edu/~bgrant/bio3d/}{http://mccammon.ucsd.edu/$\sim$bgrant/bio3d/} and wiki: \href{http://bio3d.pbwiki.com/}{http://bio3d.pbwiki.com/}.



\section{Prequisites}

Bio3D is a project to develop innovative software tools for use in computational biology.  It is based on the R language ({\url www.r-project.org}).  You should already be quite familiar with R before using Bio3D. There are several on--line resources that can help you get started using R. They can be found from the R website.  Some users find this a very steep learning curve; your experience may be similar.

Bio3D provides flexible interactive tools for carrying out a number of different structural bioinformatics tasks. Some of these may not be as fast as other analysis tools (since they are interactive) and often reflect current ideas. Most can be improved and interested users should file bug reports and feature requests on the Bio3D mailing list.


We welcome collaboration in many different forms. These include fixes or additions to the package and help on different projects that are currently underway.


\subsection{How to report a bug}

Please provide enough information for us to help you. This typically
includes the platform (windows, Unix, Macintosh) that you are using as
well as version numbers for R and for the package that seems to be
working incorrectly.

Include a small complete example that can be run and demonstrates the
problem. In some cases it is also important that you describe what you
thought you should get.

Please note:
\begin{itemize}
\item bugs in R should be reported to the R community
\item missing features are not bugs -- they are feature requests.
\end{itemize}

\section{Bioconductor Design}

Bio3D relies on the R package system to distribute code and
data. Most functions use S3 or, more recently, S4 methods and classes (as described in {\em
  Programming with Data} by J. M. Chambers). This adherence to object
oriented programming makes it easier to build component software and
helps to deal with the complexity of the data.


\subsection{Getting Started}
Start R, load the bio3d package and use the command \texttt{lbio3d()} to list th
e current functions available within the package:

<<>>=
library(bio3d)
lbio3d()
@
Detailed documentation and example code for each function can be accessed via th
e \texttt{help()} and \texttt{example()} commands (e.g. \texttt{help(read.pdb)})
.  You can also copy and paste any of the example code from the documentation of
 a particular function, or indeed this vignette, directly into your R session.

\section{Reading Example Trajectory Data}


\section{Session Information}
The version number of R and packages loaded for generating the vignette were:

\begin{verbatim}
<<echo=FALSE,results=tex>>=
sessionInfo()
@
\end{verbatim}

\begin{thebibliography}{9}


\bibitem[Grant \emph{et al.}, 2006]{grant06}
Grant, B.J. and Rodrigues, A.P.D.C and Elsawy, K.M. and Mccammon, A.J. and Caves
, L.S.D. (2006)
\textbf{Bio3d: an R package for the comparative analysis of protein structures.}
\emph{Bioinformatics},
\textbf{22}, 2695--2696.


\bibitem[Humphrey \emph{et al.}, 1996]{vmd}
Humphrey, W., et al. (1996)
\textbf{VMD: visual molecular dynamics.}
\emph{J. Mol. Graph}, \textbf{14}, 33--38


\end{thebibliography}


\end{document}
