---
title: "bio3d Vignettes"
date: "Sep 15 2016"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{bio3d Vignettes}
  \usepackage[utf8]{inputenc}
---

We distribute a number of extended **Bio3D vignettes** that provide worked examples of using Bio3D to perform a particular type of structural bioinformatics analysis. An updated list of these can be found <a href="http://thegrantlab.org/bio3d/tutorials">on-line</a>.

At the time of writing these include:

* Installing Bio3D ( <a href="http://thegrantlab.org/bio3d/phocadownload/vignettes/Bio3D_install.pdf">PDF</a> | <a href="http://thegrantlab.org/bio3d/tutorials/installing-bio3d">HTML</a>)
* Getting started with Bio3D ( PDF | <a href="http://thegrantlab.org/bio3d/user-guide">HTML</a> )
* PDB structure manipulation and analysis with Bio3D ( <a href="http://thegrantlab.org/bio3d/phocadownload/vignettes/Bio3D_pdb.pdf">PDF</a> | <a href="http://thegrantlab.org/bio3d/tutorials/structure-analysis">HTML</a>)
* Comparative sequence and structure analysis with Bio3D ( <a href="http://thegrantlab.org/bio3d/phocadownload/vignettes/Bio3D_pca.pdf">PDF</a> | <a href="http://thegrantlab.org/bio3d/tutorials/principal-component-analysis">HTML</a>)
* Beginning trajectory analysis with Bio3D ( <a href="http://thegrantlab.org/bio3d/phocadownload/vignettes/Bio3D_md.pdf">PDF</a> | <a href="http://thegrantlab.org/bio3d/tutorials/trajectory-analysis">HTML</a>)
* Enhanced methods for Normal Mode Analysis with Bio3D ( <a href="http://thegrantlab.org/bio3d/phocadownload/vignettes/Bio3D_nma.pdf">PDF</a> | <a href="http://thegrantlab.org/bio3d/tutorials/normal-mode-analysis">HTML</a>)
* Ensemble NMA of E.coli DHFR structures ( <a href="http://thegrantlab.org/bio3d/phocadownload/vignettes/Bio3D_nma-dhfr-partI.pdf">PDF</a> | <a href="http://thegrantlab.org/bio3d/tutorials/ensemble-nma-part-1">HTML</a> )
* Ensemble NMA across multiple species of DHFR ( <a href="http://thegrantlab.org/bio3d/phocadownload/vignettes/Bio3D_nma-dhfr-partII.pdf">PDF</a> | <a href="http://thegrantlab.org/bio3d/tutorials/ensemble-nma-part-2">HTML</a> )
* Correlation network analysis with Bio3D ( <a href="http://thegrantlab.org/bio3d/phocadownload/vignettes/Bio3D_cna-transducin.pdf">PDF</a> | <a href="http://thegrantlab.org/bio3d/tutorials/ensemble-nma-part-1/81-vignettes/87-correlation-network-analysis-with-bio3d">HTML</a> )
* Protein structure network analysis with Bio3D ( <a href="http://thegrantlab.org/bio3d/phocadownload/vignettes/cna_vignette.pdf">PDF</a> | <a href="http://thegrantlab.org/bio3d/tutorials/protein-structure-networks">HTML</a> )

There is also extensive <a href="http://thegrantlab.org/bio3d/html/index.html">on-line documentation</a> with worked examples (and their output) for all functions and a <a href="http://thegrantlab.org/bio3d/bio3d.pdf">package manual</a> (in PDF format) that is a concatenation of each functions documentation (without example output).

Note that for information on Bio3D development status or to report a bug, please refer to: https://bitbucket.org/Grantlab/bio3d
