FROM rocker/r-ver:3.5.0

MAINTAINER Xinqiu Yao "xinqiu.yao@gmail.com"

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /bio3d

RUN apt-get update && apt-get install -y \
    sudo \
    gdebi-core \
    pandoc \
    pandoc-citeproc \
    libssl-dev \
    libcurl4-openssl-dev \
    libssh2-1-dev \
    libxml2-dev \
    netcdf-bin \ 
    libnetcdf-dev \ 
    wget \
    muscle \
    pymol \
    git \
    qpdf
#    libgit2-dev


# Install for X11 support
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
     libx11-6 \
     libxss1 \
     libxt6 \
     libxext6 \
     libsm6 \
     libice6 \
     xdg-utils \
  && rm -rf /var/lib/apt/lists/*


# Download and install dssp
RUN wget ftp://ftp.cmbi.ru.nl/pub/software/dssp/dssp-2.0.4-linux-amd64 -O /usr/bin/dssp && \
    chmod +x /usr/bin/dssp

# Download and install stride
RUN wget http://webclu.bio.wzw.tum.de/stride/stride.tar.gz && \
    mkdir stride && cd stride && tar xvfz ../stride.tar.gz && \
    make  && cp stride /usr/bin && cd ..

RUN wget http://lcb.infotech.monash.edu.au/mustang/mustang_v3.2.3.tgz && \
    tar xvfz mustang_v3.2.3.tgz && cd MUSTANG_v3.2.3  && \
    make && cp bin/mustang-3.2.3 /usr/bin/mustang && cd ..


#setup R configs
RUN echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile

COPY devtools_1.8.0.tar.gz /bio3d
COPY staticdocs_0.1.tar.gz /bio3d

# Install required R packages
RUN R -e "install.packages(c('knitr', 'igraph', 'ncdf4', 'XML', 'bigmemory', 'BiocManager', 'rmarkdown'))"
RUN R -e "install.packages(c('httr', 'RCurl', 'memoise', 'whisker', 'rstudioapi', 'roxygen2', 'rversions', 'git2r'))"
#RUN R -e "install.packages('devtools')"
RUN R -e "install.packages('devtools_1.8.0.tar.gz', repos=NULL)"
RUN R -e "devtools::install_version('git2r', version = '0.21.0')"
RUN R -e "devtools::install_version('roxygen2', version = '5.0.1')"
RUN R -e "devtools::install_version('RCurl', version = '1.95-4.12')"
RUN R -e "devtools::install_version('testthat', version = '0.9.1')"
RUN R -e "install.packages('highlight')"
RUN R -e "install.packages('staticdocs_0.1.tar.gz', repos=NULL)"
RUN R -e "BiocManager::install(c('msa', 'Biostrings'))"

CMD ["/bin/bash", "-c", "git clone https://bitbucket.org/Grantlab/bio3d.git; \
                         cd bio3d/ver_devel/util; chmod a+x *.sh;             \ 
                         ./run_generate_html.sh;                              \
                         cp -r sandbox/* /tmp/bio3d; chmod -R a+rw /tmp/bio3d/*"] 
