# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.read_crd <- function(filename) {
    .Call('bio3d_read_crd', PACKAGE = 'bio3d', filename)
}

.read_pdb <- function(filename, multi = FALSE, hex = FALSE, maxlines = -1L, atoms_only = FALSE) {
    .Call('bio3d_read_pdb', PACKAGE = 'bio3d', filename, multi, hex, maxlines, atoms_only)
}

.read_prmtop <- function(filename) {
    .Call('bio3d_read_prmtop', PACKAGE = 'bio3d', filename)
}

